| DUPLICATE IPS | # OF DUPS |
|---|---|
|162.142.125.135|3 |
|162.142.125.224|2 |
|162.142.125.247|2 |
|162.142.125.248|2 |
|193.163.125.211|2 |
----------------------

| first instance ip | time |
|---|---|
|45.142.193.69| 2025-01-19 17:12:16.672609-05:00	 |

| last instance ip | time |
|---|---|
|162.142.125.247| 2025-01-19 18:59:43.951563-05:00		 |

* all data is taken from one specific day
---------------------------------------

| # of nulls | columns |
|---|---|
|81| city	 |
|15| tcp	 |
|97| icmp|

------------------------------------------------------
traffic scanner columns: zmap, masscan, mirai, tcp, icmp

core columns: sourceip, packets, bytes, first, last, uniquedests, port

------------------------------------

probematic records:
--------------------
 we will delete the duplicated rows because we only need one recorded instance for each case, but we need to ensure that each case is repeated and not a unique intance. But we wont touch the null values, the row still has valuable information so deleting it will lose that data and we dont want to fill the cell in with assumed data that would be innacurate.

 -------------------------------------------------------
 Sensitive Identifiers:
 ---------------------

 We will replace all IP addresses with different numerical values ranging from 1 - 200

 -------------------------------------------------------

 Traffic Volume:
 ---------------
  Observed activity surged from 1 record at 5 PM to 99 records at 6 PM EST.
  
Top Protocols and Destination Ports:
  ---------------------
 Port 0 was the most targeted port with 4 hits, followed by high ports like 53016 and 54049. TCP traffic heavily dominated the sample with 85 records, compared to just 3 ICMP records.

Data Continuity:
-----------------

0 missing intervals for temporal collection gaps across our time window, verifying that observation continuity was fully maintained.

In [ ]:
from google.colab import files
import pandas as pd

uploaded = files.upload()
df = pd.read_csv('Darknet.csv')
df.head()

Saving Darknet.csv to Darknet.csv

,SourceIP,Port,Traffic,First,Last,Packets,Bytes,UniqueDests,UniqueDest24s,Lat,...,ASN,Org,Prefix,RDNS,Zmap,Masscan,Mirai,Samples,TCP,ICMP
0,162.142.125.247,53016,16,2025-01-19T18:54:20.880283-05:00,2025-01-19T18:54:20.880283-05:00,1,66,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-23.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA001cAACkRphaijn33I0bU...,NaN,NaN
1,162.142.125.135,54049,11,2025-01-19T18:49:51.724255-05:00,2025-01-19T18:50:47.726526-05:00,2,148,2,2,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-01.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA8RXcAADcG3+Gijn2HI0Ib...,TCPSYN,NaN
2,193.163.125.199,27009,11,2025-01-19T18:32:42.122835-05:00,2025-01-19T18:55:41.283257-05:00,5,300,5,5,51.4964,...,211298,Driftnet Ltd,193.163.125.0/24,['keen.census.internet-measurement.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFKAAsjyMAAPYGv4HBo33HI0QT...,TCPSYN,NaN
3,162.142.125.254,7122,16,2025-01-19T18:49:51.809154-05:00,2025-01-19T18:49:51.809154-05:00,1,304,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-23.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAEi964AACkRpP2ijn3+I0aw...,NaN,NaN
4,162.142.125.224,57806,11,2025-01-19T18:58:00.682569-05:00,2025-01-19T18:58:00.682569-05:00,1,74,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-25.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA8L3AAADcGEdeijn3gI0P+...,TCPSYN,NaN

In [ ]:
# all column names

print(df.columns.tolist())

df.shape

['SourceIP', 'Port', 'Traffic', 'First', 'Last', 'Packets', 'Bytes', 'UniqueDests', 'UniqueDest24s', 'Lat', 'Long', 'Country', 'City', 'ASN', 'Org', 'Prefix', 'RDNS', 'Zmap', 'Masscan', 'Mirai', 'Samples', 'TCP', 'ICMP']

(100, 23)

In [ ]:
#finding the earliest instances
df['First'] = pd.to_datetime(df['First'])

start = df.sort_values('First')
start.head()

,SourceIP,Port,Traffic,First,Last,Packets,Bytes,UniqueDests,UniqueDest24s,Lat,...,ASN,Org,Prefix,RDNS,Zmap,Masscan,Mirai,Samples,TCP,ICMP
22,45.142.193.69,36388,11,2025-01-19 17:12:16.672609-05:00,2025-01-19T18:51:54.725799-05:00,719,43140,719,29,45.9968,...,214295,Skynet Network Ltd,45.142.193.0/24,[],False,True,False,['AAAAAAAGyOfwUz/wCABFSAAobs0AAPEGCO8tjsFFI0c/...,TCPSYN,NaN
2,193.163.125.199,27009,11,2025-01-19 18:32:42.122835-05:00,2025-01-19T18:55:41.283257-05:00,5,300,5,5,51.4964,...,211298,Driftnet Ltd,193.163.125.0/24,['keen.census.internet-measurement.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFKAAsjyMAAPYGv4HBo33HI0QT...,TCPSYN,NaN
36,107.152.32.62,7699,11,2025-01-19 18:37:38.715398-05:00,2025-01-19T18:56:53.199406-05:00,5,300,5,4,37.7510,...,11878,TZULO,107.152.32.0/24,[],False,True,False,['AAAAAAAGyOfwUz/wCABFAAAozxIAAPcGYK5rmCA+I0Lk...,TCPSYN,NaN
18,193.163.125.211,56001,11,2025-01-19 18:39:14.198375-05:00,2025-01-19T18:52:59.324092-05:00,3,180,3,3,51.4964,...,211298,Driftnet Ltd,193.163.125.0/24,['evocative.census.internet-measurement.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAAsUg0AAPIG4nnBo33TI0Qx...,TCPSYN,NaN
29,47.251.86.165,12555,11,2025-01-19 18:41:47.278493-05:00,2025-01-19T18:50:09.83899-05:00,3,198,3,3,34.0544,...,45102,"Alibaba US Technology Co., Ltd.",47.251.0.0/17,[],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA0RwVAADEGbHov+1alI0Hs...,TCPSYN,NaN

In [ ]:
#finding the last instances
df['Last'] = pd.to_datetime(df['Last'])

start = df.sort_values('Last')
start.tail()

,SourceIP,Port,Traffic,First,Last,Packets,Bytes,UniqueDests,UniqueDest24s,Lat,...,ASN,Org,Prefix,RDNS,Zmap,Masscan,Mirai,Samples,TCP,ICMP
42,162.142.125.247,62173,16,2025-01-19 18:59:43.951563-05:00,2025-01-19 18:59:43.951563-05:00,1,66,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-23.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA0A0cAACkRS1Wijn33I0D/...,NaN,NaN
38,193.163.125.209,31402,11,2025-01-19 18:59:44.779250-05:00,2025-01-19 18:59:44.779250-05:00,1,60,1,1,51.4964,...,211298,Driftnet Ltd,193.163.125.0/24,['empathetic.census.internet-measurement.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAAsBPcAAPIGG9nBo33RI0BF...,TCPSYN,NaN
9,147.185.132.156,10001,11,2025-01-19 18:58:47.003199-05:00,2025-01-19 18:59:45.966278-05:00,1296,77760,1296,934,37.7510,...,396982,GOOGLE-CLOUD-PLATFORM,147.185.132.0/22,[],True,False,False,['AAAAAAAGyOfwUz/wCABFYAAs1DEAAPgGlYyTuYScI0Id...,TCPSYN,NaN
25,162.142.125.135,37815,11,2025-01-19 18:59:55.180074-05:00,2025-01-19 18:59:55.180074-05:00,1,74,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-01.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA8tDcAADcGPFaijn2HI0RP...,TCPSYN,NaN
93,193.163.125.16,3130,11,2025-01-19 18:58:31.564213-05:00,2025-01-19 18:59:55.567981-05:00,2,120,2,2,51.4964,...,211298,Driftnet Ltd,193.163.125.0/24,['electrifying.census.internet-measurement.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFKAAs1SQAAPYGyDLBo30QI0LF...,TCPSYN,NaN

In [ ]:
#checking for duplactes


df[df.duplicated(subset=["SourceIP"], keep=False)].sort_values("SourceIP")

,SourceIP,Port,Traffic,First,Last,Packets,Bytes,UniqueDests,UniqueDest24s,Lat,...,ASN,Org,Prefix,RDNS,Zmap,Masscan,Mirai,Samples,TCP,ICMP
1,162.142.125.135,54049,11,2025-01-19 18:49:51.724255-05:00,2025-01-19 18:50:47.726526-05:00,2,148,2,2,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-01.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA8RXcAADcG3+Gijn2HI0Ib...,TCPSYN,NaN
25,162.142.125.135,37815,11,2025-01-19 18:59:55.180074-05:00,2025-01-19 18:59:55.180074-05:00,1,74,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-01.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA8tDcAADcGPFaijn2HI0RP...,TCPSYN,NaN
64,162.142.125.135,36081,11,2025-01-19 18:56:24.861368-05:00,2025-01-19 18:56:24.861368-05:00,1,74,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-01.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA8mJcAADcG81Oijn2HI0S0...,TCPSYN,NaN
4,162.142.125.224,57806,11,2025-01-19 18:58:00.682569-05:00,2025-01-19 18:58:00.682569-05:00,1,74,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-25.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA8L3AAADcGEdeijn3gI0P+...,TCPSYN,NaN
82,162.142.125.224,47182,11,2025-01-19 18:50:21.580519-05:00,2025-01-19 18:50:21.580519-05:00,1,74,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-25.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA8eRAAADcGzXKijn3gI0T5...,TCPSYN,NaN
0,162.142.125.247,53016,16,2025-01-19 18:54:20.880283-05:00,2025-01-19 18:54:20.880283-05:00,1,66,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-23.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA001cAACkRphaijn33I0bU...,NaN,NaN
42,162.142.125.247,62173,16,2025-01-19 18:59:43.951563-05:00,2025-01-19 18:59:43.951563-05:00,1,66,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-23.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA0A0cAACkRS1Wijn33I0D/...,NaN,NaN
62,162.142.125.248,49943,16,2025-01-19 18:55:36.347674-05:00,2025-01-19 18:55:36.347674-05:00,1,70,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-23.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAA45tgAACkRccSijn34I0T1...,NaN,NaN
74,162.142.125.248,12374,16,2025-01-19 18:49:36.592209-05:00,2025-01-19 18:49:36.592209-05:00,1,60,1,1,37.7510,...,398324,CENSYS-ARIN-01,162.142.125.0/24,['scanner-23.ch1.censys-scanner.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAAd20gAACkRvCSijn34I0a2...,NaN,NaN
13,193.163.125.211,4438,11,2025-01-19 18:50:03.150885-05:00,2025-01-19 18:50:03.150885-05:00,1,60,1,1,51.4964,...,211298,Driftnet Ltd,193.163.125.0/24,['evocative.census.internet-measurement.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFKAAszqQAAPYG5PjBo33TI0Ou...,TCPSYN,NaN
18,193.163.125.211,56001,11,2025-01-19 18:39:14.198375-05:00,2025-01-19 18:52:59.324092-05:00,3,180,3,3,51.4964,...,211298,Driftnet Ltd,193.163.125.0/24,['evocative.census.internet-measurement.com.'],False,False,False,['AAAAAAAGyOfwUz/wCABFAAAsUg0AAPIG4nnBo33TI0Qx...,TCPSYN,NaN

In [ ]:
df.isnull().sum()

SourceIP          0
Port              0
Traffic           0
First             0
Last              0
Packets           0
Bytes             0
UniqueDests       0
UniqueDest24s     0
Lat               0
Long              0
Country           0
City             81
ASN               0
Org               0
Prefix            0
RDNS              0
Zmap              0
Masscan           0
Mirai             0
Samples           0
TCP              15
ICMP             97
dtype: int64

In [ ]:
df.dtypes

SourceIP                            object
Port                                 int64
Traffic                              int64
First            datetime64[ns, UTC-05:00]
Last             datetime64[ns, UTC-05:00]
Packets                              int64
Bytes                                int64
UniqueDests                          int64
UniqueDest24s                        int64
Lat                                float64
Long                               float64
Country                             object
City                                object
ASN                                  int64
Org                                 object
Prefix                              object
RDNS                                object
Zmap                                  bool
Masscan                               bool
Mirai                                 bool
Samples                             object
TCP                                 object
ICMP                                object
dtype: object